### ISSUE TITLE
Any testing with Chromecast 2?

### ISSUE THREAD

**Issue by Ivshti** [thibauts/node-castv2-client#47]
Hello,

Has anyone tested node-castv2-client on chromecast 2?

I received this error logs from Stremio users with Chromecast 2. They say it can be re-produced on a regular basis, meanwhile the original Chromecast is working with the app fine.

```
Error: Load failed(…)
Uncaught TypeError: Cannot read property 'mediaSessionId' of null
Uncaught Error: Illegal wire type for field Message.Field
.extensions.api.cast_channel.CastMessage.payload_type: 5 (0 expected)
Uncaught Error: Illegal wire type for unknown field 13 in Message
.extensions.api.cast_channel.CastMessage#decode: 7
Uncaught Error: Illegal number of bytes for Message.Field
.extensions.api.cast_channel.CastMessage.payload_binary: 99 required but
got only 96
Uncaught Error: Illegal wire type for unknown field 13 in Message
.extensions.api.cast_channel.CastMessage#decode: 7
castplayer Error: Device timeout(…)
```

This probably doesn't give enough information to directly go and debug the issue, but it may offer some guidelines.

**Comment by thibauts** [comment]
Looks like the protobuf schema was updated. The new version should be
available in an up to date chromium source tree.

**Comment by veplus** [comment]
I can give you the full error log if needed.
Regards

**Comment by Ivshti** [comment]
@veplus I think that's the full info that came from node-castv2. Others are stremio errors/messages

**Comment by veplus** [comment]
No, i could developpe the error log

**Comment by thibauts** [comment]
No need for more logs, the problem most certainly is the protobuf schema was updated.

As said above, it can be found in the chromium source tree. Make a PR and I'll review it.

**Comment by Ten10** [comment]
Hello there,
Do you have an estimate on how long it will take to fix the issue?
Thanks

**Comment by thibauts** [comment]
I don't have a Chromecast 2 so I can't reproduce the issue. We need someone having one and willing to investigate.

Does one of the repo watchers have one and is willing to invest a little time to provide a fix to the community ? I'll provide guidance in the code and concepts if needed.

**Comment by Ten10** [comment]
Here is  some more information...
I tried to set up the castv2 environment but I ended up using a different api to communicate with chromecast 2.
I was able to play the bigbunny example video without any problems on my chromecast 2.

Now to stremio:
When running them in cmd they output a server url and when you select a stream in the UI they print the relative url of that stream.
If you combine that url and load it in the browser then the tab shows the video.
I then took that link and replaced it in the load command.
The load was sent and no real reply was received.

I think it might the bug is related to the server which does the streaming.

Hope this helps.
I will try to set up castv2 environment to retest the differences.

**Comment by Ten10** [comment]
Managed to get the castv2 environment set up.
Encountering same issues.
* The big bunny video casts without a hitch.
* When replacing the link to a stremio link the I receive the load failed error.

I think the problem is with the stremio server which serves the chromecast and not with the castv2 module.

Let me know if you need anything else.

**Comment by thibauts** [comment]
It could be the server, yes. Though, keep in mind Chromecasts supports only webm(/mkv) and mp4 containers, containing h246, AAC and mp3 streams. The file you tested with could be plain unreadable by Chromecasts.

**Comment by Ten10** [comment]
It turns out that chromecast uses google dns servers and not the router dns server.
Meaning a server running on localhost cannot be reached by chromecast.
I confirmed that was the issue with me anyway by testing the theory using a tunneling service like ngrok.

**Comment by thibauts** [comment]
Show me the link that doesn't work.
